version: '3'

services:
  vpn:
    #image: hwdsl2/ipsec-vpn-server
    build: .
    restart: always
    env_file:
      - ./vpn.env
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
      - "1701:1701/udp"
      - "3000:3000/tcp"
      - "4000:4000/tcp"
    privileged: true
    hostname: ipsec-vpn-server
    container_name: ipsec-vpn-server
